#!/usr/bin/env python3
# Copyright 2024 Bytedance Ltd. and/or its affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Promote a local HF-format checkpoint directory to the root of an HF model repo,
and upload a generated model card. Called by _upload_model_to_hf.sh with env vars:
  LOCAL_DIR    — path to the local huggingface/ dir (config.json + shards)
  REPO_ID      — target HF model repo
  BASE_MODEL   — Hub id of the base student (e.g. google/gemma-3-4b-it)
  TEACHER_REPO — teacher repo id (default: JWei05/dapo-gemma3-27b-it)
  TEACHER_STEP — teacher subfolder (default: step_000040)
"""

import os
import sys
import tempfile

from huggingface_hub import HfApi

REPO_ID = os.environ["REPO_ID"]
LOCAL_DIR = os.environ["LOCAL_DIR"]
BASE_MODEL = os.environ.get("BASE_MODEL", "google/gemma-3-4b-it")
TEACHER_REPO = os.environ.get("TEACHER_REPO", "JWei05/dapo-gemma3-27b-it")
TEACHER_STEP = os.environ.get("TEACHER_STEP", "step_000040")
SFT_DATASET = "JWei05/DAPO-Gemma3-27B-IT-RL-SFT-Data"
SIZE_TAG = "12B" if "12b" in REPO_ID.lower() else "4B"


def main():
    if not os.path.isfile(os.path.join(LOCAL_DIR, "config.json")):
        print(f"ERROR: {LOCAL_DIR}/config.json not found", file=sys.stderr)
        return 1
    api = HfApi()

    size_mb = (
        sum(
            os.path.getsize(os.path.join(LOCAL_DIR, f))
            for f in os.listdir(LOCAL_DIR)
            if os.path.isfile(os.path.join(LOCAL_DIR, f))
        )
        / 1e6
    )
    print(f"uploading {LOCAL_DIR} ({size_mb:.0f} MB) -> {REPO_ID}/ (root)")
    api.upload_folder(
        folder_path=LOCAL_DIR,
        path_in_repo="",
        repo_id=REPO_ID,
        repo_type="model",
        commit_message="promote final distilled ckpt (step 200) to repo root",
    )

    readme = f"""---
license: gemma
base_model: {BASE_MODEL}
datasets:
- {SFT_DATASET}
tags:
- gemma3
- math
- sft
---

# {REPO_ID.split("/")[-1]}

SFT of **Gemma 3 {SIZE_TAG} IT** on math responses generated by a DAPO-RL-trained
**Gemma 3 27B** teacher over the DAPO-Math-17k prompt set.

## Recipe

- **Student base**: [{BASE_MODEL}](https://huggingface.co/{BASE_MODEL})
- **SFT data source (teacher responses)**: [{TEACHER_REPO}](https://huggingface.co/{TEACHER_REPO})
  at subfolder `{TEACHER_STEP}` (Gemma 3 27B IT after DAPO RL on math)
- **SFT dataset**: [{SFT_DATASET}](https://huggingface.co/datasets/{SFT_DATASET})
  — 16,000 training prompts × 2 teacher responses = 32,000 rows (seed=42 split)
- **Objective**: standard cross-entropy SFT on teacher-sampled tokens
- **Schedule**: 200 steps · batch 128 (micro=16 per GPU × 8 × B200) · cosine LR
  `1e-5 → 1e-6` with 20-step linear warmup · `clip_grad=1.0` · `weight_decay=0.1`
  · `seed=42`
- **Hardware**: 1× B200 node (8 GPUs), FSDP2

## Load

```python
from transformers import AutoModelForCausalLM, AutoTokenizer

model = AutoModelForCausalLM.from_pretrained("{REPO_ID}", torch_dtype="bfloat16")
tokenizer = AutoTokenizer.from_pretrained("{REPO_ID}")
```

## Intermediate checkpoints

Saves were written every 50 steps as subfolders:
`step_000050/`, `step_000100/`, `step_000150/`, `step_000200/`.

Load one with `subfolder=` e.g.:
```python
AutoModelForCausalLM.from_pretrained("{REPO_ID}", subfolder="step_000150",
                                     torch_dtype="bfloat16")
```

The repo root is the final checkpoint (`step_000200`).

## License

Gemma derivative — subject to the [Gemma terms of use](https://ai.google.dev/gemma/terms).
"""

    with tempfile.NamedTemporaryFile("w", suffix=".md", delete=False) as f:
        f.write(readme)
        readme_path = f.name
    print("uploading README.md …")
    api.upload_file(
        path_or_fileobj=readme_path,
        path_in_repo="README.md",
        repo_id=REPO_ID,
        repo_type="model",
        commit_message="add model card",
    )
    print(f"DONE → https://huggingface.co/{REPO_ID}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
